---
- hosts: all
  remote_user: vagrant
  become: true
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
  - name: Statrt service httpd, if not started
    service:
      name: httpd
      state: started
  - name: Create an index.html page
    copy:
      content: "\n\n\n\n\n Created on 2 AM 25-AUG using Ansible \n After fixing passwordless authentication \n\n test auto push\n\n\n\n\n"
      dest: /var/www/html/index.html

