---
- hosts: all
  remote_user: vagrant
  become: true
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
  - name: Statrt service httpd, if not started
    service:
      name: httpd
      state: started
  - name: Create an index.html page
    copy:
      content: "Created on 5PM 24-AUG using Ansible \n After fixing passwordless authentication \n\n test auto push"
      dest: /var/www/html/index.html

